//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEvolution.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chamados
    {
        public string Cod_Chamado { get; set; }
        public string Desc_Chamado { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Cod_Produto { get; set; }
        public string Cod_Atendimento { get; set; }
    
        public virtual TipoAtendimento TipoAtendimento { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
