//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEvolution.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Produto = new HashSet<Produto>();
        }
    
        public string Cod_Cliente { get; set; }
        public string Nome { get; set; }
        public string Razao_Social { get; set; }
        public string CPF { get; set; }
        public string CNPJ { get; set; }
        public string Email_Contato { get; set; }
        public string End_Completo { get; set; }
        public string Telefone { get; set; }
        public string Stat_Cliente { get; set; }
        public string ID_usuario { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Produto> Produto { get; set; }
    }
}
