//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEvolution.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionario
    {
        public string Cod_Funcionario { get; set; }
        public string Nome_Completo { get; set; }
        public string Nome_Tratamento { get; set; }
        public string CPF { get; set; }
        public string End_Completo { get; set; }
        public string Email_Contato { get; set; }
        public string Telefone { get; set; }
        public string Stat_Funcionario { get; set; }
        public string ID_usuario { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
