//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEvolution.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        public Produto()
        {
            this.Chamados = new HashSet<Chamados>();
        }
    
        public string Cod_Produto { get; set; }
        public string Desc_Produto { get; set; }
        public string Cod_Cliente { get; set; }
    
        public virtual ICollection<Chamados> Chamados { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
